# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=10, null=True)),
                ('TimeDate', models.DateTimeField(null=True)),
                ('Map', models.URLField(max_length=20, null=True)),
                ('Lat', models.FloatField(null=True)),
                ('Long', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='car_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trip', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='car_details',
            name='Trip_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car_id'),
        ),
    ]
